spring.application.name=UserService
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${USER_SERVICE_DB_URL}
spring.datasource.username=${USER_SERVICE_DB_USERNAME}
spring.datasource.password=${USER_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=trace
server.port=${USER_SERVICE_PORT}
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}
AWS_LOG_REGION=${AWS_LOG_REGION}


